version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: dt22
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: messages
    ports:
      - "5432:5432" 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 

  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000" # Map the container's port 3000 to the host machine's port 3000
    environment:
      DATABASE_URL: postgres://dt22:1234@postgres:5432/messages # Connection string to PostgreSQL
