version: '3.8'

services:
  node-app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - PORT=8081
      - DATABASE_USER=dt22
      - DATABASE_HOST=postgres
      - DATABASE_NAME=postgres
      - DATABASE_PASSWORD=1234
      - DATABASE_PORT=5432

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: dt22
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
