version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    ports:
      - "5432:5432" 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 

  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"
